### ISSUE TITLE
Initial Task List

### ISSUE THREAD

**Issue by nahidacm** [MagentoSellerCentral/SellerCentralBackend#1]
- [ ] Install latest Magento on localhost.

- [ ] Pull this module.

- [ ] Start development.

- [ ] Install new Magento instance on GC
